spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: CNL
    password: CNL
  application:
    name: jms-camel

camel:
  springboot:
    main-run-controller: true

#jc:
#  aggregate:
#    enabled: false
#  unique:
#    enabled: false

