name: jms-camel

services:

  mq:
    image: apache/activemq-artemis:latest
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ARTEMIS_USER=CNL
      - ARTEMIS_PASSWORD=CNL

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  redis-gui:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"