name: jms-camel

services:

  app:
    image: ghcr.io/markwigmans/jms-camel:latest
    environment:
      - SPRING_ARTEMIS_BROKER-URL="tcp://mq:61616"
      - SPRING_DATA_REDIS_HOST="redis"
      - JC_AGGREGATE_REDIS_ENDPOINT="redis:6379"
      - JC_AGGREGATE_TIMER_PERIOD=100
    depends_on:
      - mq
      - redis
    restart: on-failure

  mq:
    image: apache/activemq-artemis:latest
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ARTEMIS_USER=CNL
      - ARTEMIS_PASSWORD=CNL

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  redis-gui:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"